name: sandbox
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.7 <4.0.0'

# все що використовується для коду, який йде у випуск
dependencies:
  http: ^1.1.0

# все що використовується для коду, який не йде у випуск
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  http: ^1.1.0
